### ISSUE TITLE
113-04-39 missing NOTE 2 text

### ISSUE THREAD

**Issue by ronaldtse** [paneron/iev-data-subset#3]
From IEC:

> I noticed that the entry for [113-04-39](http://www.electropedia.org/iev/iev.nsf/display?openform&ievref=113-04-39) had text missing in Note 2: NOTE 2 The name “thermal transmittance” and the symbol

<img width="746" alt="Screenshot 2021-02-26 at 1 37 29 AM" src="https://user-images.githubusercontent.com/11865/109193314-32432c80-77d3-11eb-9feb-674fad125d4d.png">

Original:
<img width="671" alt="Screenshot 2021-02-26 at 1 38 37 AM" src="https://user-images.githubusercontent.com/11865/109193479-5acb2680-77d3-11eb-9ec8-4a9de280a27e.png">

This may be related to iev-data.

**Comment by strogonoff** [comment]
Looking into this. May be related to temporary loss of some fields, including notes.

**Comment by strogonoff** [comment]
Fixed now by @yablokov
