### ISSUE TITLE
Synonym has “preferred” flag

### ISSUE THREAD

**Issue by strogonoff** [paneron/iev-data-subset#4]
Only one designation is supposed to be preferred, but in this case a synonym is also “preferred”, which is confusing:

https://iev.demo.paneron.org/eng/localized-concept/45c1f76b-589b-59d2-b592-9d2174b0c676/

Will confirm with @yablokov that this issue comes from the original iev-data, and file there.

**Comment by ronaldtse** [comment]
@strogonoff according to ISO 10241-1:

<img width="989" alt="Screenshot 2021-03-02 at 2 36 26 AM" src="https://user-images.githubusercontent.com/11865/109542497-16f05e00-7b00-11eb-9521-9b551d6a15dc.png">

<img width="1071" alt="Screenshot 2021-03-02 at 2 36 49 AM" src="https://user-images.githubusercontent.com/11865/109542543-253e7a00-7b00-11eb-828a-487be14f8935.png">

Especially:
> Note 1 to entry: There can be more than one preferred term. If there is only one term representing the concept in a terminological entry of a standard, this term is automatically preferred. By analogy, “preferred” can apply also to symbols and appellations.

A symbol's "preferred" normative status is allowed outside the preferred term, and that multiple preferred terms (and symbols) are allowed.

**Comment by strogonoff** [comment]
Hmm, I thought I recalled it being otherwise but I guess I’m mistaken…
